apiVersion : apps/v1
kind: Deployment
metadata:
  name: devopsdemo85
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsdemo85
  template:
    metadata:
      labels:
        app: devopsdemo85
    spec:
      containers:
        - name: devopsdemo85
          image: devopsdemo85.azurecr.io/devopsdemo85
          ports:
          - containerPort: 8080
